spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ticket_system_db
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver 

  data:
    redis:
      host: localhost
      port: 6379

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect


jwt:
  secret: 6A2A49E3F2F7C96B8E1A5C3D9E7F4A8B6C2D5F1E9A7B3C6D
  access-expiration: 900000
  refresh-expiration: 604800000
